// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleTutorialWebApplication.DbContexts;

#nullable disable

namespace SimpleTutorialWebApplication.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    partial class CityInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("SimpleTutorialWebApplication.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Most popular city in the whole New South Wales.",
                            Name = "Sydney"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A major hub including china town.",
                            Name = "Burwood"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A quite suburb with waterfronts to Parammatta River.",
                            Name = "Rhodes"
                        });
                });

            modelBuilder.Entity("SimpleTutorialWebApplication.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointOfInterests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "A view of harbor illuminated with lights and other attractions.",
                            Name = "Darling Harbor"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "A location for food and enjoyment with access to Ferries.",
                            Name = "Barangaroo"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "A collection of shops and entertainment from asian culture.",
                            Name = "China town"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Description = "A green park to carry out some fitness routine and to get your body moving with some extra curricular activities.",
                            Name = "Burwood Park"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            Description = "A great water side view of the Paramatta river.",
                            Name = "Water side"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 3,
                            Description = "A park for casual workout and enjoy the Paramatta river.",
                            Name = "Mill Park"
                        });
                });

            modelBuilder.Entity("SimpleTutorialWebApplication.PointOfInterest", b =>
                {
                    b.HasOne("SimpleTutorialWebApplication.Entities.City", "City")
                        .WithMany("PointOfInterests")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("SimpleTutorialWebApplication.Entities.City", b =>
                {
                    b.Navigation("PointOfInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
